# Generated by Django 6.0.4 on 2026-06-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='selected_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
