# Generated by Django 6.0.4 on 2026-07-05 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must contain only letters and spaces.', regex='^[A-Za-z ]+$')])),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01, message='Price must be greater than zero.')])),
                ('description', models.TextField(max_length=200, validators=[django.core.validators.RegexValidator(message='Description can only contain letters, numbers, and basic punctuation.', regex='^[A-Za-z0-9 .,!?]+$')])),
            ],
        ),
    ]
