# Generated by Django 6.0.4 on 2026-06-23 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='Description contains invalid characters.', regex='^[A-Za-z0-9 ,.!?-]+$')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name can contain only letters and spaces.', regex='^[A-Za-z ]+$')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01, message='Price must be greater than 0.')]),
        ),
    ]
