# Generated by Django 6.0.4 on 2026-06-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insert',
            name='age',
            field=models.IntegerField(),
        ),
    ]
